export const denyList = [
    '@_screenshoter',
    '@buzz_chronicles',
    '@getsummari',
    '@heyslideit',
    '@memdotai',
    '@NotionAddon',
    '@rattibha',
    '@readwise',
    '@RecuerdameBot',
    '@RemindMe_OfThis',
    '@saveflix',
    '@SaveToBookmarks',
    '@SaveToNotiom',
    '@SaveToNotion',
    '@SaveToObsidian',
    '@StoreToClickUp',
    '@threader_app',
    '@threadioapp',
    '@ThreadNotesApp',
    '@threadreaderapp',
    '@ThreadVoice',
    '@UnrollHelper',
    '@Unrollme',
    '@ZuperlyHQ',
  ].map((keyword) => keyword.toLowerCase())
